print(r"+--------------------------------------+")
print(r"|                                      |")
print(r"|                  🚀                  |")
print(r"|                  |                   |")
print(r"|                 / \                  |")
print(r"|                |   |                 |")
print(r"|               /-----\                |")
print(r"|              |   F   |               |")
print(r"|              |   A   |               |")
print(r"|              |   W   |               |")
print(r"|              |   k   |               |")
print(r"|              |   E   |               |")
print(r"|              |   S   |               |")
print(r"|              | (UwU) |               |")
print(r"|             /---------\              |")
print(r"|            /    VCET   \             |")
print(r"|           /-------------\            |")
print(r"|          |               |           |")
print(r"|          |     UGHH!!    |           |")
print(r"|         /                 \          |")
print(r"|        /   ____________    \         |")
print(r"|       /   /|           |\   \        |")
print(r"|      |   / |           | \   |       |")
print(r"|      |  /  |vvvvvvvvvvv|  \  |       |")
print(r"|      | /   |           |   \ |       |")
print(r"|      |     |           |     |       |")
print(r"|      |     |vvvvvvvvvvv|     |       |")
print(r"|            |           |             |")
print(r"|           /             \            |")
print(r"|          /               \           |")
print(r"|         /     (ꈍᴗꈍ)♡    \          |")
print(r"|        /                   \         |")
print(r"|       /\   (  ) (  ) (  )  /\        |")
print(r"|      /  \_________________/  \       |")
print(r"|     /____\               /____\      |")
print(r"|    |      |   POST      |      |     |")
print(r"|    |      |    PAND1    |      |     |")
print(r"|    |      |             |      |     |")
print(r"|    |      |  'Steal     |      |     |")
print(r"|    |      |      The    |      |     |")
print(r"|    |      |   M00000N'  |      |     |")
print(r"|   /|      |             |      |\    |")
print(r"|  / |      |             |      | \   |")
print(r"| /  |      |\___________/|      |  \  |")
print(r"||___|______|             |______|___| |")
print(r"|    ((     ))            ((     ))    |")
print(r"|   ((       ))          ((       ))   |")
print(r"|  ((    .    ))        ((    .    ))  |")
print(r"|  ((    .    ))        ((    .    ))  |")
print(r"|  ((    .    ))        ((    .    ))  |")
print(r"|   ((   .   ))          ((   .   ))   |")
print(r"|        .                    .        |")
print(r"|        .                    .        |")
print(r"|       ...                  ...       |")
print(r"|      .....     (≧◡≦)     .....      |")
print(r"|" + "ThePythonGames".center(38) +    "|")
print(r"|" + "TeAm: Fawkes".center(38) +      "|")
print(r"|" + "ObJeCt: 🚀".center(37) +        "|")
print(r"|                                      |")
print(r"+--------------------------------------+")
